/**
 * One-time Sepolia setup for a freshly deployed Election:
 * setAdminSigner → addParty (×N) → startElection
 *
 * Usage (from contracts/):
 *   bun ../node_modules/.bin/tsx scripts/setup-election.ts
 *   # or: node --import tsx scripts/setup-election.ts
 *
 * Requires contracts/.env: SEPOLIA_RPC_URL, PRIVATE_KEY (deployer/admin)
 * Optional root .env: ADMIN_SIGNER_PRIVATE_KEY (generated if missing)
 * Requires root .env: NEXT_PUBLIC_ELECTION_ADDRESS
 */
import { config as loadEnv } from "dotenv";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { appendFileSync, existsSync, readFileSync } from "node:fs";
import {
  createPublicClient,
  createWalletClient,
  http,
  getAddress,
  isAddress,
  type Hex,
} from "viem";
import { privateKeyToAccount, generatePrivateKey } from "viem/accounts";
import { sepolia } from "viem/chains";

const __dirname = dirname(fileURLToPath(import.meta.url));
const contractsRoot = resolve(__dirname, "..");
const appRoot = resolve(contractsRoot, "..");

loadEnv({ path: resolve(contractsRoot, ".env") });
loadEnv({ path: resolve(appRoot, ".env") });

const electionAbi = [
  {
    type: "function",
    name: "setAdminSigner",
    stateMutability: "nonpayable",
    inputs: [{ name: "signer", type: "address" }],
    outputs: [],
  },
  {
    type: "function",
    name: "addParty",
    stateMutability: "nonpayable",
    inputs: [
      { name: "name", type: "string" },
      { name: "shortCode", type: "string" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "startElection",
    stateMutability: "nonpayable",
    inputs: [],
    outputs: [],
  },
  {
    type: "function",
    name: "adminSigner",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "address" }],
  },
  {
    type: "function",
    name: "partyCount",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "state",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint8" }],
  },
] as const;

/** Keep names/order aligned with lib/parties.ts DEMO_PARTIES (index == party id). */
const PARTIES = [
  { name: "Harbor Alliance", shortCode: "HA" },
  { name: "Civic Forward", shortCode: "CF" },
  { name: "Green Commons", shortCode: "GC" },
  { name: "Unity Independent", shortCode: "UI" },
] as const;

function readEnvKey(name: string): string | undefined {
  const value = process.env[name];
  if (!value || value.includes("YOUR_")) return undefined;
  return value;
}

function ensureAdminSignerKey(): Hex {
  const existing = readEnvKey("ADMIN_SIGNER_PRIVATE_KEY");
  if (existing) {
    return (existing.startsWith("0x") ? existing : `0x${existing}`) as Hex;
  }

  const generated = generatePrivateKey();
  const envPath = resolve(appRoot, ".env");
  appendFileSync(
    envPath,
    `\n# Backend eligibility signer (generated by setup-election.ts)\nADMIN_SIGNER_PRIVATE_KEY=${generated}\n`,
  );
  console.log(`Generated ADMIN_SIGNER_PRIVATE_KEY and appended to ${envPath}`);
  return generated;
}

async function main() {
  const rpcUrl = readEnvKey("SEPOLIA_RPC_URL");
  const adminKeyRaw = readEnvKey("PRIVATE_KEY");
  const electionRaw = readEnvKey("NEXT_PUBLIC_ELECTION_ADDRESS");

  if (!rpcUrl || !adminKeyRaw || !electionRaw || !isAddress(electionRaw)) {
    throw new Error(
      "Need SEPOLIA_RPC_URL + PRIVATE_KEY (contracts/.env) and NEXT_PUBLIC_ELECTION_ADDRESS (root .env)",
    );
  }

  const adminKey = (
    adminKeyRaw.startsWith("0x") ? adminKeyRaw : `0x${adminKeyRaw}`
  ) as Hex;
  const electionAddress = getAddress(electionRaw);
  const adminAccount = privateKeyToAccount(adminKey);
  const signerKey = ensureAdminSignerKey();
  const signerAccount = privateKeyToAccount(signerKey);

  const publicClient = createPublicClient({
    chain: sepolia,
    transport: http(rpcUrl),
  });
  const walletClient = createWalletClient({
    account: adminAccount,
    chain: sepolia,
    transport: http(rpcUrl),
  });

  console.log("Admin (deployer):", adminAccount.address);
  console.log("Election:        ", electionAddress);
  console.log("Admin signer:    ", signerAccount.address);

  const [currentSigner, partyCount, state] = await Promise.all([
    publicClient.readContract({
      address: electionAddress,
      abi: electionAbi,
      functionName: "adminSigner",
    }),
    publicClient.readContract({
      address: electionAddress,
      abi: electionAbi,
      functionName: "partyCount",
    }),
    publicClient.readContract({
      address: electionAddress,
      abi: electionAbi,
      functionName: "state",
    }),
  ]);

  const stateLabel = ["NotStarted", "Registration", "Active", "Closed"][
    Number(state)
  ];
  console.log(`Current state=${stateLabel} parties=${partyCount}`);

  if (currentSigner === "0x0000000000000000000000000000000000000000") {
    const hash = await walletClient.writeContract({
      address: electionAddress,
      abi: electionAbi,
      functionName: "setAdminSigner",
      args: [signerAccount.address],
    });
    await publicClient.waitForTransactionReceipt({ hash });
    console.log("setAdminSigner ✓", hash);
  } else {
    console.log("adminSigner already set:", currentSigner);
  }

  if (partyCount === 0n) {
    for (const party of PARTIES) {
      const hash = await walletClient.writeContract({
        address: electionAddress,
        abi: electionAbi,
        functionName: "addParty",
        args: [party.name, party.shortCode],
      });
      await publicClient.waitForTransactionReceipt({ hash });
      console.log(`addParty ${party.shortCode} ✓`, hash);
    }
  } else {
    console.log(`Skipping addParty (${partyCount} already registered)`);
  }

  if (Number(state) < 2) {
    const hash = await walletClient.writeContract({
      address: electionAddress,
      abi: electionAbi,
      functionName: "startElection",
    });
    await publicClient.waitForTransactionReceipt({ hash });
    console.log("startElection ✓", hash);
  } else {
    console.log("Election already Active/Closed");
  }

  const finalState = await publicClient.readContract({
    address: electionAddress,
    abi: electionAbi,
    functionName: "state",
  });
  const finalParties = await publicClient.readContract({
    address: electionAddress,
    abi: electionAbi,
    functionName: "partyCount",
  });

  console.log(
    `\nDone. state=${["NotStarted", "Registration", "Active", "Closed"][Number(finalState)]} parties=${finalParties}`,
  );
  console.log("Restart bun dev and refresh /results — demo banner should be gone.");
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
